[versions]
agp = "8.7.3"
kotlin = "2.1.0"

maplibre = "11.6.1"
maplibre-geojson = "7.0.0-pre0"
#343269b2
maplibre-navigation = "5.0.0-pre10"
#411fb14c

coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
navigationUiAndroid = "5.0.0-pre10"
play-services-location = "21.3.0"




[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.9" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.8.4" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.8.4" }

navigation-ui-android = { module = "org.maplibre.navigation:navigation-ui-android", version.ref = "navigationUiAndroid" }
okhttp =  { group = "com.squareup.okhttp3", name ="okhttp", version = "4.12.0" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location"}


# MapLibre
maplibre = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }
maplibre-geojson = { group = "org.maplibre.gl", name = "geojson", version.ref = "maplibre-geojson" }
maplibre-turf = { group = "org.maplibre.gl", name = "services-turf", version.ref = "maplibre-geojson" }
maplibre-navigation-core ={ group = "org.maplibre.navigation", name = "navigation-core", version.ref = "maplibre-navigation" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


